Attempt to batch toggleGroupDataItems with redux-batched-actions
unfoldingWord/translationCore pull request #4874
Opened 2018-08-09 00:31 UTC by klappy

#### Describe what your pull request addresses (Please include relevant issue numbers):
https://github.com/unfoldingWord-dev/translationCore/issues/4842
Addresses slow loading of the book of Acts in the Alignment tool.

#### Please include detailed Test instructions for your pull request:
- Load the book of Acts from this project: https://git.door43.org/lrsallee/en_act.git
- Load the wordAlignment tool and ensure it loads both under 20s and menu acts as expected.
- Load other projects and tools and ensure all works well.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2018-08-09 00:54 UTC, dsm-git commented
[Linux build 1.0.0 (736b45c)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-736b45c.zip) is ready for download.
[macOS build 1.0.0 (736b45c)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-736b45c.dmg) is ready for download.
[Windows x64 build 1.0.0 (736b45c)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-736b45c.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (736b45c)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-736b45c.setup.exe) is ready for download.

2018-08-09 02:20 UTC, mannycolon approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4874#-:-LJRTb0JBap6ob0yGosS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PhotoNomad0 and @neutrinog)



<!-- Sent from Reviewable.io -->

2018-08-09 17:52 UTC, da1nerd requested changes

2018-08-09 17:52 UTC, neutrinog commented on src/js/actions/GroupsDataActions.js
> +  return action;
Action will be `undefined` if the default case is matched.
You should provide a default value for action.

2018-08-09 23:35 UTC, dsm-git commented
[Linux build 1.0.0 (1656dea)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-1656dea.zip) is ready for download.
[macOS build 1.0.0 (1656dea)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-1656dea.dmg) is ready for download.
[Windows x64 build 1.0.0 (1656dea)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-1656dea.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (1656dea)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-1656dea.setup.exe) is ready for download.

2018-08-10 20:36 UTC, da1nerd approved these changes

2018-08-10 21:24 UTC, dsm-git commented
[Linux build 1.0.0 (8e76ccd)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-8e76ccd.zip) is ready for download.
[macOS build 1.0.0 (8e76ccd)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-8e76ccd.dmg) is ready for download.
[Windows x64 build 1.0.0 (8e76ccd)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-8e76ccd.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (8e76ccd)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-8e76ccd.setup.exe) is ready for download.

2018-08-10 21:44 UTC, neutrinog commented
This also resolves https://github.com/unfoldingWord-dev/translationCore/issues/4673

2018-08-10 21:53 UTC, da1nerd reviewed
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/4874)* status: all files reviewed, 1 unresolved discussion (waiting on @neutrinog and @PhotoNomad0)



<!-- Sent from Reviewable.io -->

2018-08-10 21:54 UTC, neutrinog commented
Confirmed this works well on Linux.

2018-08-10 22:05 UTC, dsm-git commented
[Linux build 1.0.0 (ca376d9)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-ca376d9.zip) is ready for download.
[macOS build 1.0.0 (ca376d9)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-ca376d9.dmg) is ready for download.
[Windows x64 build 1.0.0 (ca376d9)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-ca376d9.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (ca376d9)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-ca376d9.setup.exe) is ready for download.

2018-08-11 10:34 UTC, PhotoNomad0 commented
CLosing - Needs to be based off of release 0.10.0

2018-08-11 10:34 UTC, closed without merging

2018-08-11 10:56 UTC, PhotoNomad0 commented
Replaced with https://github.com/unfoldingword-dev/translationcore/pull/4882

2018-09-28 20:15 UTC, neutrinog commented
@klappy do you need this branch anymore? If not could you delete it?