WIP: Source content updater UI
unfoldingWord/translationCore pull request #4929
Opened 2018-08-22 20:41 UTC by mannycolon

#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2018-08-22 21:03 UTC, dsm-git commented
[Linux build 1.0.0 (27d5e18)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-27d5e18.zip) is ready for download.
[macOS build 1.0.0 (27d5e18)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-27d5e18.dmg) is ready for download.
[Windows x64 build 1.0.0 (27d5e18)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-27d5e18.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (27d5e18)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-27d5e18.setup.exe) is ready for download.

2018-08-22 21:21 UTC, dsm-git commented
[Linux build 1.0.0 (55eef75)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-55eef75.zip) is ready for download.
[macOS build 1.0.0 (55eef75)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-55eef75.dmg) is ready for download.
[Windows x64 build 1.0.0 (55eef75)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-55eef75.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (55eef75)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-55eef75.setup.exe) is ready for download.

2018-08-24 11:41 UTC, PhotoNomad0 commented
Tests failing

2018-08-24 11:53 UTC, PhotoNomad0 reviewed
Source Looks good, just a minor change suggestion.  Will test now.

2018-08-24 11:53 UTC, PhotoNomad0 commented on src/js/actions/AlertModalActions.js
> +export function openOptionDialog(alertMessage, callback, button1Text, button2Text, buttonLinkText = null, callback2) {
callback2 - probably add `= null`

2018-08-24 19:51 UTC, dsm-git commented
[Linux build 1.0.0 (780a909)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-780a909.zip) is ready for download.
[macOS build 1.0.0 (780a909)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-780a909.dmg) is ready for download.
[Windows x64 build 1.0.0 (780a909)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-780a909.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (780a909)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-780a909.setup.exe) is ready for download.

2018-08-24 20:10 UTC, PhotoNomad0 requested changes

2018-08-24 20:10 UTC, PhotoNomad0 commented on src/js/helpers/sourceContentUpdatesHelpers.js
> +        const tHelpsLatestVersion = getLatestVersionInPath(tHelpResource);
Need to add check for null value being returned if no versions found.

2018-08-24 20:10 UTC, PhotoNomad0 commented on src/js/helpers/sourceContentUpdatesHelpers.js
> +        const bibleLatestVersion = getLatestVersionInPath(bibleIdPath);
Need to add check for null value being returned if no versions found.

2018-08-28 13:43 UTC, dsm-git commented
[Linux build 1.0.0 (4eeea0c)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-4eeea0c.zip) is ready for download.
[macOS build 1.0.0 (4eeea0c)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-4eeea0c.dmg) is ready for download.
[Windows x64 build 1.0.0 (4eeea0c)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-4eeea0c.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (4eeea0c)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-4eeea0c.setup.exe) is ready for download.

2018-08-28 14:13 UTC, dsm-git commented
[Linux build 1.0.0 (0cf0128)](https://tc-builds.door43.org/translationCore-linux-x64-1.0.0-0cf0128.zip) is ready for download.
[macOS build 1.0.0 (0cf0128)](https://tc-builds.door43.org/translationCore-macos-x64-1.0.0-0cf0128.dmg) is ready for download.
[Windows x64 build 1.0.0 (0cf0128)](https://tc-builds.door43.org/translationCore-win-x64-1.0.0-0cf0128.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (0cf0128)](https://tc-builds.door43.org/translationCore-win-x32-1.0.0-0cf0128.setup.exe) is ready for download.

2018-08-28 19:32 UTC, merged