Tool Optimization
unfoldingWord/translationCore pull request #5127
Opened 2018-10-01 18:17 UTC by RoyalSix

#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR has some optimizations for the tool opening 

#### Please include detailed Test instructions for your pull request:
- Try opening a fresh Acts project on develop and record the time.
- Try opening a fresh Acts project on this branch and record the time, it should be faster
.
#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2018-10-01 18:59 UTC, dsm-git commented
[Linux build 1.0.0 (c44004d)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-linux-x64-1.0.0-c44004d.deb) is ready for download.
[macOS build 1.0.0 (c44004d)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-macos-x64-1.0.0-c44004d.dmg) is ready for download.
[Windows x64 build 1.0.0 (c44004d)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-win-x64-1.0.0-c44004d.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (c44004d)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-win-x32-1.0.0-c44004d.setup.exe) is ready for download.

2018-10-02 18:30 UTC, dsm-git commented
[Linux build 1.0.0 (3224286)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-linux-x64-1.0.0-3224286.deb) is ready for download.
[macOS build 1.0.0 (3224286)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-macos-x64-1.0.0-3224286.dmg) is ready for download.
[Windows x64 build 1.0.0 (3224286)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-win-x64-1.0.0-3224286.setup.exe) is ready for download.
[Windows x32 build 1.0.0 (3224286)](https://tc-builds.door43.org/build/feature-jay-5111/translationCore-win-x32-1.0.0-3224286.setup.exe) is ready for download.

2018-10-03 19:39 UTC, mannycolon requested changes

2018-10-03 19:39 UTC, mannycolon commented on gulpfile.js
> +
@RoyalSix Hey any specific reason why you're editing the gulp file?

2018-10-03 19:39 UTC, mannycolon commented on package.json
> +    "lodash.throttle": "^4.1.1",
:+1:

2018-10-03 19:39 UTC, mannycolon commented on scripts/deb/DEBIAN/postinst
> +xdg-icon-resource install --size 128 /opt/translationcore/translationcore-128.png unfoldingword-translationcore
@RoyalSix You have a bunch of new files that make me think you branch off of develop branch. is this correct?

2018-10-03 21:31 UTC, mannycolon commented
# Tool loading time:

## Acts project
  - `wA tool:` 17sec
  - `tW tool:` 22sec

## Titus project
  - `wA tool:` 7sec
  - `tW tool:` 8sec

2018-10-03 21:32 UTC, merged