WIP: feature 5134
unfoldingWord/translationCore pull request #5472
Opened 2018-11-23 16:29 UTC by PhotoNomad0

#### Describe what your pull request addresses (Please include relevant issue numbers):
- updated en lexicon for hebrew.

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2018-11-23 17:01 UTC, dsm-git commented
[Linux build 1.1.0 (9eed184)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-9eed184.deb) is ready for download.
[macOS build 1.1.0 (9eed184)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-9eed184.dmg) is ready for download.
[Windows x64 build 1.1.0 (9eed184)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-9eed184.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (9eed184)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-9eed184.setup.exe) is ready for download.

2018-11-30 00:45 UTC, dsm-git commented
[Linux build 1.1.0 (b34d282)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-b34d282.deb) is ready for download.
[macOS build 1.1.0 (b34d282)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-b34d282.dmg) is ready for download.
[Windows x64 build 1.1.0 (b34d282)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-b34d282.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b34d282)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-b34d282.setup.exe) is ready for download.

2018-11-30 01:09 UTC, dsm-git commented
[Linux build 1.1.0 (1a583d3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-1a583d3.deb) is ready for download.
[macOS build 1.1.0 (1a583d3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-1a583d3.dmg) is ready for download.
[Windows x64 build 1.1.0 (1a583d3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-1a583d3.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (1a583d3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-1a583d3.setup.exe) is ready for download.

2018-12-01 13:04 UTC, dsm-git commented
[Linux build 1.1.0 (51a0402)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-51a0402.deb) is ready for download.
[macOS build 1.1.0 (51a0402)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-51a0402.dmg) is ready for download.
[Windows x64 build 1.1.0 (51a0402)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-51a0402.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (51a0402)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-51a0402.setup.exe) is ready for download.

2018-12-01 17:47 UTC, dsm-git commented
[Linux build 1.1.0 (2599a10)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-2599a10.deb) is ready for download.
[macOS build 1.1.0 (2599a10)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-2599a10.dmg) is ready for download.
[Windows x64 build 1.1.0 (2599a10)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-2599a10.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (2599a10)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-2599a10.setup.exe) is ready for download.

2018-12-03 14:46 UTC, PhotoNomad0 commented
Created in wrong repo.

2018-12-03 15:38 UTC, dsm-git commented
[Linux build 1.1.0 (d82140d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-d82140d.deb) is ready for download.
[macOS build 1.1.0 (d82140d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-d82140d.dmg) is ready for download.
[Windows x64 build 1.1.0 (d82140d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-d82140d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (d82140d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-d82140d.setup.exe) is ready for download.

2018-12-04 14:55 UTC, dsm-git commented
[Linux build 1.1.0 (c06438b)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-c06438b.deb) is ready for download.
[macOS build 1.1.0 (c06438b)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-c06438b.dmg) is ready for download.
[Windows x64 build 1.1.0 (c06438b)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-c06438b.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c06438b)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-c06438b.setup.exe) is ready for download.

2018-12-04 18:47 UTC, RoyalSix commented
@PhotoNomad0 I started opening wA like specified in the instructions and it crashed before the tool opened.
![image](https://user-images.githubusercontent.com/16184018/49465264-09798b80-f7b2-11e8-9eca-a94077210b7e.png)

2018-12-04 19:26 UTC, richmahn commented
@RoyalSix We found this problem too, discussed here https://team43.slack.com/archives/G1P0SKR6W/p1543871421101100

2018-12-04 23:45 UTC, mannycolon commented
Please merge w/ latest develop branch, resolve merge conflict & make sure you're not overwriting the correct tools commit hash numbers

2018-12-05 03:22 UTC, richmahn commented
@PhotoNomad0 Update to have the commit id of wordAlignment's develop branch

2018-12-05 12:09 UTC, dsm-git commented
[Linux build 1.1.0 (b2361da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-b2361da.deb) is ready for download.
[macOS build 1.1.0 (b2361da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-b2361da.dmg) is ready for download.
[Windows x64 build 1.1.0 (b2361da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-b2361da.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (b2361da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-b2361da.setup.exe) is ready for download.

2018-12-05 12:46 UTC, dsm-git commented
[Linux build 1.1.0 (c3d88c9)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-c3d88c9.deb) is ready for download.
[macOS build 1.1.0 (c3d88c9)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-c3d88c9.dmg) is ready for download.
[Windows x64 build 1.1.0 (c3d88c9)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-c3d88c9.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (c3d88c9)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-c3d88c9.setup.exe) is ready for download.

2018-12-05 15:46 UTC, dsm-git commented
[Linux build 1.1.0 (8cc6430)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-8cc6430.deb) is ready for download.
[macOS build 1.1.0 (8cc6430)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-8cc6430.dmg) is ready for download.
[Windows x64 build 1.1.0 (8cc6430)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-8cc6430.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8cc6430)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-8cc6430.setup.exe) is ready for download.

2018-12-05 19:02 UTC, dsm-git commented
[Linux build 1.1.0 (e853eab)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-e853eab.deb) is ready for download.
[macOS build 1.1.0 (e853eab)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-e853eab.dmg) is ready for download.
[Windows x64 build 1.1.0 (e853eab)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-e853eab.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e853eab)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-e853eab.setup.exe) is ready for download.

2018-12-05 23:03 UTC, dsm-git commented
[Linux build 1.1.0 (5ffa6da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-5ffa6da.deb) is ready for download.
[macOS build 1.1.0 (5ffa6da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-5ffa6da.dmg) is ready for download.
[Windows x64 build 1.1.0 (5ffa6da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-5ffa6da.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (5ffa6da)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-5ffa6da.setup.exe) is ready for download.

2018-12-06 00:06 UTC, richmahn commented
No lexicons are showing for words with Strongs.

2018-12-06 17:01 UTC, dsm-git commented
[Linux build 1.1.0 (fc0895f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-fc0895f.deb) is ready for download.
[macOS build 1.1.0 (fc0895f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-fc0895f.dmg) is ready for download.
[Windows x64 build 1.1.0 (fc0895f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-fc0895f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (fc0895f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-fc0895f.setup.exe) is ready for download.

2018-12-06 19:25 UTC, dsm-git commented
[Linux build 1.1.0 (e36b6a3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-e36b6a3.deb) is ready for download.
[macOS build 1.1.0 (e36b6a3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-e36b6a3.dmg) is ready for download.
[Windows x64 build 1.1.0 (e36b6a3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-e36b6a3.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (e36b6a3)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-e36b6a3.setup.exe) is ready for download.

2018-12-07 16:10 UTC, dsm-git commented
[Linux build 1.1.0 (4211159)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-4211159.deb) is ready for download.
[macOS build 1.1.0 (4211159)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-4211159.dmg) is ready for download.
[Windows x64 build 1.1.0 (4211159)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-4211159.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (4211159)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-4211159.setup.exe) is ready for download.

2018-12-08 02:52 UTC, dsm-git commented
[Linux build 1.1.0 (106fd69)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-106fd69.deb) is ready for download.
[macOS build 1.1.0 (106fd69)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-106fd69.dmg) is ready for download.
[Windows x64 build 1.1.0 (106fd69)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-106fd69.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (106fd69)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-106fd69.setup.exe) is ready for download.

2018-12-08 05:55 UTC, mannycolon submitted a review, later dismissed

2018-12-08 06:07 UTC, mannycolon commented
@PhotoNomad0 Don't you have to write migrations to auto copy the `En UHL lexicons`  from `tcResources` to the user resources directory

2018-12-08 06:36 UTC, dsm-git commented
[Linux build 1.1.0 (8b4fc9d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-8b4fc9d.deb) is ready for download.
[macOS build 1.1.0 (8b4fc9d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-8b4fc9d.dmg) is ready for download.
[Windows x64 build 1.1.0 (8b4fc9d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-8b4fc9d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8b4fc9d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-8b4fc9d.setup.exe) is ready for download.

2018-12-08 12:30 UTC, dsm-git commented
[Linux build 1.1.0 (8715a39)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-8715a39.deb) is ready for download.
[macOS build 1.1.0 (8715a39)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-8715a39.dmg) is ready for download.
[Windows x64 build 1.1.0 (8715a39)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-8715a39.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (8715a39)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-8715a39.setup.exe) is ready for download.

2018-12-08 15:20 UTC, PhotoNomad0 commented
@mannycolon - added copying of missing lexicons.  Ready for review.

2018-12-08 15:44 UTC, dsm-git commented
[Linux build 1.1.0 (0d2835d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-0d2835d.deb) is ready for download.
[macOS build 1.1.0 (0d2835d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-0d2835d.dmg) is ready for download.
[Windows x64 build 1.1.0 (0d2835d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-0d2835d.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (0d2835d)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-0d2835d.setup.exe) is ready for download.

2018-12-08 21:53 UTC, mannycolon requested changes

2018-12-08 21:53 UTC, mannycolon commented on src/js/pages/app.js
> +    const tcResourcesPath = path.join(ospath.home(), 'translationCore', 'resources');
Please removed these changes. they are not the reason why tools are loading correctly.

2018-12-08 21:53 UTC, mannycolon commented on src/js/pages/app.js
> +    if (localStorage.getItem('version') !== packageJson.version || !fs.existsSync(tcResourcesPath)) {
same here

2018-12-08 22:05 UTC, mannycolon requested changes

2018-12-08 22:05 UTC, mannycolon commented on src/js/helpers/ResourcesHelpers.js
> +export function getMissingUnzippedResources(subPath) {
This function does not follow the DRY principle. it's basically a copy of the code in getMissingResources() which means making unnecessary file systems (fs) calls. I would suggest moving the specific code that copies the missing files, to the getMissingResources() function.

2018-12-08 22:05 UTC, mannycolon commented on src/js/helpers/ResourcesHelpers.js
> +        const sourceResources = path.join(tcResourcesPath, languageId);
This logic here can be converted into a small function and reference in getMissingResources() wherever it would make sense

2018-12-09 00:59 UTC, dsm-git commented
[Linux build 1.1.0 (ec3884f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-linux-x64-1.1.0-ec3884f.deb) is ready for download.
[macOS build 1.1.0 (ec3884f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-macos-x64-1.1.0-ec3884f.dmg) is ready for download.
[Windows x64 build 1.1.0 (ec3884f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x64-1.1.0-ec3884f.setup.exe) is ready for download.
[Windows x32 build 1.1.0 (ec3884f)](https://tc-builds.door43.org/build/feature-mcleanb-5134/translationCore-win-x32-1.1.0-ec3884f.setup.exe) is ready for download.

2018-12-10 03:31 UTC, mannycolon approved these changes

2018-12-10 03:50 UTC, merged