Bug fixes for invalidation checking
unfoldingWord/translationCore pull request #6122
Opened 2019-06-04 18:04 UTC by RoyalSix

#### Describe what your pull request addresses (Please include relevant issue numbers):
-

#### Please include detailed Test instructions for your pull request:
-

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2019-06-04 18:26 UTC, dsm-git commented
[Linux build 1.2.0 (6323764)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-linux-x64-1.2.0-6323764.deb) is ready for download.
[macOS build 1.2.0 (6323764)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-macos-x64-1.2.0-6323764.dmg) is ready for download.
[Windows x64 build 1.2.0 (6323764)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-win-x64-1.2.0-6323764.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (6323764)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-win-x32-1.2.0-6323764.setup.exe) is ready for download.

2019-06-06 16:48 UTC, dsm-git commented
[Linux build 1.2.0 (17bec16)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-linux-x64-1.2.0-17bec16.deb) is ready for download.
[macOS build 1.2.0 (17bec16)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-macos-x64-1.2.0-17bec16.dmg) is ready for download.
[Windows x64 build 1.2.0 (17bec16)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-win-x64-1.2.0-17bec16.setup.exe) is ready for download.
[Windows x32 build 1.2.0 (17bec16)](https://tc-builds.door43.org/build/feature-jay-5941/translationCore-win-x32-1.2.0-17bec16.setup.exe) is ready for download.

2019-06-10 17:44 UTC, mannycolon commented
Local Test: `LGTM`

2019-06-10 17:48 UTC, mannycolon requested changes

2019-06-10 17:48 UTC, mannycolon commented on src/js/actions/ToolActions.js
> +        //TRICKY: need to verify groups data before and after the contextId has been loaded
Why not only once and after loading the contextId?

2019-06-10 17:48 UTC, mannycolon commented on src/js/actions/ToolActions.js
> +        //TRICKY: need to verify groups data before and after the contextId has been loaded
Why can't we verify groups data once just after loading the context id?

2019-06-10 18:28 UTC, RoyalSix reviewed
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6122)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @mannycolon)

___
*[src/js/actions/ToolActions.js, line 80 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6122#-LgYeW3TItbAhIMNjC0y-r2-80:-Lh1cJnI48fMEbqEejCJ:b-4p8yx8) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/17bec16d728c42281ec46540683becb441662428/src/js/actions/ToolActions.js#L80)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Why can't we verify groups data once just after loading the context id?
</blockquote></details>

Some reason if I only call that method after it will not work. There is definitely something more complex about why this isn't working like it should but I was unable to figure it out. If I remember correctly the underlying issue was that I could not determine once a change was written to the FS from the redux subscriber method so some other action that reads from the FS was using old data. I also tried using a timeout but that did not work. This was the best I could come up with for now. This will only get called twice on the tool loading.


<!-- Sent from Reviewable.io -->

2019-06-10 21:13 UTC, mannycolon commented
@RoyalSix I guess we'll have to address that somewhere else or at another time

2019-06-10 21:13 UTC, mannycolon approved these changes

2019-06-10 21:13 UTC, merged