New Crowdin translations
unfoldingWord/translationCore pull request #6210
Opened 2019-07-06 05:41 UTC by neutrinog

Enjoy!

2019-07-06 11:16 UTC, PhotoNomad0 requested changes
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @neutrinog)

___
*[src/locale/Kannada-kn_IN.json, line 184 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210#-Lj5ziVOE0hPmRTUjnYy:-Lj5ziVP8a66YA0UALyn:b-os64f4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f6030f58799f32fc2608383df4f7a79152ef6d93/src/locale/Kannada-kn_IN.json#L184)):*
> ```JSON
>     "not_usfm_file_error": "ನೀವು ಆಯ್ಕೆ ಮಾಡಿದ ಯೋಜನೆಯು (${ಯೋಜನೆ_ಮಾರ್ಗ} ಬೆಲೆಯಿಲ್ಲದ ಅಥವಾ ಕೆಲಸಕ್ಕೆಬಾರದ ಯುಎಸ್.ಎಫ್.ಎಂ. ಯೋಜನೆಯಾಗಿದೆ. ${The project you selected (${project_path}) is an invalid USFM project. ",
>     "local_import_error": "ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಇಳಿಸಿಕೊಳ್ಳುತ್ತಿರುವಾಗ ಸಮಸ್ಯೆ ಕಂಡುಬಂದಿದೆ. <ಬಿಆರ್ />${ಮಾರ್ಗದಿಂದ} ${ಮಾರ್ಗಕ್ಕೆ} ಯೋಜನೆಯನ್ನು ಕಳುಹಿಸಬೇಡಿರಿ. ${Error occurred while importing your project.<br />Could not move the project from ${fromPath} to ${toPath}",
>     "online_import_error": "ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಇಳಿಸಿಕೊಳ್ಳುತ್ತಿರುವಾಗ ಸಮಸ್ಯೆ ಕಂಡುಬಂದಿದೆ. <ಬಿಆರ್ />${ಯೋಜನೆ_ಯುಆರ್.ಎಲ್}ಯಿಂದ ${ಮಾರ್ಗಕ್ಕೆ} ಯೋಜನೆಯನ್ನು ಇಳಿಸಿಕೊಳ್ಳುವುದಕ್ಕಾಗುವುದಿಲ್ಲ. ${Error occurred while importing your project.<br />Could not download the project from ${project_url} to ${toPath}",
> ```

Variable Identifiers should not be translated.
___
*[src/locale/Kannada-kn_IN.json, line 386 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210#-Lj5zqzu-bTD4G4lqE4W:-Lj5zqzu-bTD4G4lqE4X:brkw6k9) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/f6030f58799f32fc2608383df4f7a79152ef6d93/src/locale/Kannada-kn_IN.json#L386)):*
> ```JSON
>     "continue_button": "ಮುಂದುವರೆ ${Continue}",
>     "continue_import_button": "ಇಳಿಸಿಕೊಳ್ಳುವುದನ್ನು ಮುಂದುವರೆ ${Continue Import}",
>     "d43_login_button": "${ಬಾಗಿಲು43} ರಿಂದ ಸಂಪರ್ಕ ಪಡೆ ${Log in with ${door43}}",
> ```

Too much text for a button


<!-- Sent from Reviewable.io -->

2019-07-07 11:00 UTC, PhotoNomad0 requested changes
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @neutrinog)

___
*[src/locale/Kannada-kn_IN.json, line 170 at r2](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210#-LjB4hJy-MQTQpE0X4na:-LjB4hJy-MQTQpE0X4nb:bw3fhvb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/987940ce9634413262df6ad86b7670169a9ae23b/src/locale/Kannada-kn_IN.json#L170)):*
> ```JSON
>     "upload_successful_alert": "${ಬಳಕೆದಾರರ ಹೆಸರು}, ನಿಮ್ಮ ಯೋಜನೆಯು ಯಶಸ್ವಿಯಾಗಿ ಮೇಲಕ್ಕೆ ಏರಿಸಲ್ಪಟ್ಟಿದೆ. ${${username}, your project was successfully uploaded.",
>     "upload_modified_error": "${ಯೋಜನೆ_ಹೆಸರು} ಮೇಲಕ್ಕೆ ಏರಿಸಲ್ಪಟ್ಟಿಲ್ಲ ಯಾಕಂದರೆ ನಿಮ್ಮ ${ಬಾಗಿಲು43} ಖಾತೆಯಲ್ಲಿರುವ ಯೋಜನೆಯ ಅನುವಾದಕ್ಕೆ ಬದಲಾವಣೆಗಳಿವೆ. ${${project_name} cannot be uploaded because there have been changes to the translation of that project on your ${door43} account.",
>     "merge_export_error": "ಈ ಯೋಜನೆಯು ಸಂಘರ್ಷಣೆಗಳನ್ನು ಒಳಗೊಂಡಿದೆ ಮತ್ತು ಮೇಲಕ್ಕೆ ಏರಿಸುವುದಕ್ಕಾಗುವದಿಲ್ಲ. ವಿಲೀನವಾಗಿರುವ ಸಂಘರ್ಷಣೆಗಳನ್ನು ಪರಿಷ್ಕಾರ ಮಾಡುವುದಕ್ಕೆ ಯೋಜನೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿಕೊಳ್ಳಿರಿ, ಆದನಂತರ ಮತ್ತೊಂದುಬಾರಿ ಪ್ರಯತ್ನಿಸಿರಿ. ${This project has merge conflicts and cannot be exported. Select the project to resolve the merge conflicts, then try again.",
> ```

Should not have English source as a variable


<!-- Sent from Reviewable.io -->

2019-07-09 20:04 UTC, PhotoNomad0 submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @neutrinog)

___
*[src/locale/Kannada-kn_IN.json, line 50 at r3](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6210#-LjNKMjs01Yx1-twMXRH:-LjNKMjs01Yx1-twMXRI:b-cbzh42) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/85c3d88573964b516c460fb0b1c8fdbc0fd6dae8/src/locale/Kannada-kn_IN.json#L50)):*
> ```JSON
>   "toggle_developer_tools": "ಅಭಿವೃದ್ಧಿ ಉಪಕರಣಗಳನ್ನು ಮಾರ್ಪಡಿಸು ${Toggle developer tools}",
>   "actions": "ಕಾರ್ಯಾಚರಣೆ ${Actions}",
>   "running_latest_version": "{app}ದ ಇತ್ತೀಚಿನ ಆವೃತ್ತಿಯನ್ನು ನೀವು ನಡೆಸುತ್ತಿದ್ದೀರ. ${You are running the latest version of ${app}.}",
> ```

Should not have English text at end of verse


<!-- Sent from Reviewable.io -->

2019-07-19 20:41 UTC, mannycolon submitted a review, later dismissed

2019-07-21 03:47 UTC, mannycolon requested changes
Fix issues with Kannada-kn_IN

2019-07-25 19:25 UTC, closed without merging