QA Fix - #6250 - fix tW missing checks by reverting category loading funcion
unfoldingWord/translationCore pull request #6268
Opened 2019-07-22 21:53 UTC by richmahn

#### Describe what your pull request addresses (Please include relevant issue numbers):
- Fixes QA Fail #6250 
- Fixed by reverting some code I myself am the one who made, but didn't allow for different book projects. Not worth caching anyway. Moved the call to that function outside of a loop so it wasn't called for every category as that wasn't needed.

#### Please include detailed Test instructions for your pull request:
- Follow the instructions in the issue using the build generated by this PR

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2019-07-22 22:22 UTC, dsm-git commented
[Linux build 2.0.0 (7678081)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-linux-x64-2.0.0-7678081.deb) is ready for download.
[macOS build 2.0.0 (7678081)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-macos-x64-2.0.0-7678081.dmg) is ready for download.
[Windows x64 build 2.0.0 (7678081)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-win-x64-2.0.0-7678081.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (7678081)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-win-x32-2.0.0-7678081.setup.exe) is ready for download.

2019-07-23 10:23 UTC, PhotoNomad0 requested changes
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6268)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @richmahn)

___
*[src/js/helpers/ProjectAPI.js, line 450 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6268#-LkTL_OW7X1ytEMMvPv_:-LkTL_OW7X1ytEMMvPva:b-yurces) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7678081dd272806ca418156dbb2bf7977cfe3690/src/js/helpers/ProjectAPI.js#L450)):*
> ```JavaScript
>   /**
>    * Gets the category mapping for a tool in the project's .categoryIndex's directory
>    * This gets cached in toolCategoryMapping by toolName
> ```

It looks like we are no longer using cache here?
___
*[src/js/helpers/ProjectAPI.js, line 460 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6268#-LkTKsgg-sh1XVGH8pTZ:-LkTKsgg-sh1XVGH8pT_:bb6k42p) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7678081dd272806ca418156dbb2bf7977cfe3690/src/js/helpers/ProjectAPI.js#L460)):*
> ```JavaScript
>     if (fs.pathExistsSync(indexPath)) {
>       try {
>         const parentCategories = fs.readdirSync(indexPath).map((fileName) => path.parse(fileName).name);
> ```

Is this necessary?  Doesn't fs.readdirSync() just return the files not the  full paths?


<!-- Sent from Reviewable.io -->

2019-07-23 10:25 UTC, PhotoNomad0 requested changes
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6268)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @richmahn)

___
*[src/js/helpers/ProjectAPI.js, line 460 at r1](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6268#-LkTM3LfEJpvoxMaZIOi:-LkTM3LfEJpvoxMaZIOj:b-de4fbq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/7678081dd272806ca418156dbb2bf7977cfe3690/src/js/helpers/ProjectAPI.js#L460)):*
> ```JavaScript
>     if (fs.pathExistsSync(indexPath)) {
>       try {
>         const parentCategories = fs.readdirSync(indexPath).map((fileName) => path.parse(fileName).name);
> ```

It doesn't seem like the map here is necessary. Doesn't fs.readdirSync() just return the file names, not the full paths?


<!-- Sent from Reviewable.io -->

2019-07-23 14:39 UTC, richmahn commented
@PhotoNomad0 The readdirSync().map() there is stripping the extension off, not the parent path, as it does just get file names with no path, but I felt easier to start with just the category name for the mapping and then add .json to it again

Either I do it there, or I do
          ```parentCategoriesObject[path.parse(category).name] = fs.readJsonSync(subCategoryPath);```
Felt the former is cleaner

2019-07-23 15:01 UTC, PhotoNomad0 approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6268)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-07-23 15:02 UTC, merged

2019-07-23 15:04 UTC, dsm-git commented
[Linux build 2.0.0 (7f59c21)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-linux-x64-2.0.0-7f59c21.deb) is ready for download.
[macOS build 2.0.0 (7f59c21)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-macos-x64-2.0.0-7f59c21.dmg) is ready for download.
[Windows x64 build 2.0.0 (7f59c21)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-win-x64-2.0.0-7f59c21.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (7f59c21)](https://tc-builds.door43.org/build/qafail-richmahn-6250/translationCore-win-x32-2.0.0-7f59c21.setup.exe) is ready for download.