Bugfix For Opening Projects With Missing Verese
unfoldingWord/translationCore pull request #6343
Opened 2019-08-07 21:03 UTC by RoyalSix

#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR addresses and issue where the ProjectValidationsContainer would not be shown when it needs to

#### Please include detailed Test instructions for your pull request:
- Test the project here and ensure it opens
[41-MAT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/3478898/41-MAT.usfm.zip)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

2019-08-07 21:29 UTC, dsm-git commented
[Linux build 2.0.0 (6d456aa)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-linux-x64-2.0.0-6d456aa.deb) is ready for download.
[macOS build 2.0.0 (6d456aa)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-macos-x64-2.0.0-6d456aa.dmg) is ready for download.
[Windows x64 build 2.0.0 (6d456aa)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-win-x64-2.0.0-6d456aa.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (6d456aa)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-win-x32-2.0.0-6d456aa.setup.exe) is ready for download.

2019-08-07 23:43 UTC, dsm-git commented
[Linux build 2.0.0 (c3cfedc)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-linux-x64-2.0.0-c3cfedc.deb) is ready for download.
[macOS build 2.0.0 (c3cfedc)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-macos-x64-2.0.0-c3cfedc.dmg) is ready for download.
[Windows x64 build 2.0.0 (c3cfedc)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-win-x64-2.0.0-c3cfedc.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c3cfedc)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-win-x32-2.0.0-c3cfedc.setup.exe) is ready for download.

2019-08-08 00:36 UTC, mannycolon approved these changes

2019-08-08 00:51 UTC, mannycolon commented
- Checking for content updates while in a tool does not work

2019-08-08 00:52 UTC, mannycolon requested changes
Checking for content updates while in a tool does not work

2019-08-08 04:53 UTC, dsm-git commented
[Linux build 2.0.0 (c22f6a0)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-linux-x64-2.0.0-c22f6a0.deb) is ready for download.
[macOS build 2.0.0 (c22f6a0)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-macos-x64-2.0.0-c22f6a0.dmg) is ready for download.
[Windows x64 build 2.0.0 (c22f6a0)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-win-x64-2.0.0-c22f6a0.setup.exe) is ready for download.
[Windows x32 build 2.0.0 (c22f6a0)](https://tc-builds.door43.org/build/bugfix-jay-6282/translationCore-win-x32-2.0.0-c22f6a0.setup.exe) is ready for download.

2019-08-08 09:34 UTC, PhotoNomad0 approved these changes
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6343)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-08 09:41 UTC, PhotoNomad0 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/unfoldingword-dev/translationcore/6343#-:-LlkagCO3sKdeo6zi8Sg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-08-08 09:44 UTC, merged