Refactor of Load Methods
unfoldingWord/translationCore pull request #956
Opened 2017-03-27 15:34 UTC by RoyalSix

#### This pull request addresses:
This PR completely refactors the loading process for our new data structure
Write a few sentences about what your pull request addresses, the relevant issue numbers, etc.

#### How to test this pull request:
Open a project and see if the props in the console are available from project loaded

2017-03-27 16:32 UTC, mannycolon commented
Reviewed 58 of 58 files at r1.
Review status: all files reviewed at latest revision, 62 unresolved discussions, some commit checks broke.

---

*[src/js/ModuleApi.js, line 244 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFPycGdleWzuOU04tQ:-KgFPycGdleWzuOU04tR:bvytepm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/ModuleApi.js#L244)):*
> ```JavaScript
>     if (manifest && projectSaveLocation) {
>       manifest[field] = data;
>       projectSaveLocation += '/tc-manifest.json';
> ```

Do we want to keep  '/manifest.json' instead 

---

*[src/js/actions/CoreActionConsts.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFRByPWKdDHC18jECr:-KgFRByPWKdDHC18jECs:bbg4950) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/CoreActionConsts.js#L17)):*
> ```JavaScript
>   ALERT_MODAL: "ALERT_MODAL",
>   ALERT_MODAL_RESPONSE: "ALERT_MODAL_RESPONSE",
>   CHANGE_CHECK_MODAL_VISIBILITY:"CHANGE_CHECK_MODAL_VISIBILITY",
> ```

this is written twice ^^^

---

*[src/js/actions/CoreActionsRedux.js, line 251 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFRmbMjkghOR1YC_F6:-KgFRmbNyG5o2I9wJpkO:b-23iopu) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/CoreActionsRedux.js#L251)):*
> ```JavaScript
> }
> 
> // export function updateCurrentCheckIndex(index){
> ```

Do we need to get rid ofn the commented code?

---

*[src/js/actions/GetDataActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSSxn-1gDLiLULqKN:-KgFSSxn-1gDLiLULqKO:b-c3ljf3) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L29)):*
> ```JavaScript
> import Path from 'path';
> 
> let api = window.ModuleApi;
> ```

this should all be constants not varaibles (let)

---

*[src/js/actions/GetDataActions.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSbAem6c3KPldyWZV:-KgFSbAem6c3KPldyWZW:b-vr544o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L42)):*
> ```JavaScript
> 
> /**
>  * Sends project path to the store
> ```

maybe add @description

---

*[src/js/actions/GetDataActions.js, line 52 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSfLW6d0-GPaPqJvx:-KgFSfLW6d0-GPaPqJvy:b-vfrkky) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L52)):*
> ```JavaScript
> 
> /**
>  * Sends project manifest to the store
> ```

same here maybe add @description

---

*[src/js/actions/GetDataActions.js, line 62 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSjx3e2AvrZca1N9B:-KgFSjx3e2AvrZca1N9C:bg6v38e) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L62)):*
> ```JavaScript
> 
> /**
>  * Sends project parameters to the store
> ```

same here ^^^  add @description

---

*[src/js/actions/GetDataActions.js, line 75 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFShvm7G2XwWOTpEyH:-KgFShvm7G2XwWOTpEyI:b-vfrkky) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L75)):*
> ```JavaScript
> 
> /**
>  * Formats and saves manifest according to tC standards, 
> ```

same here maybe add @description

---

*[src/js/actions/GetDataActions.js, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSosvR-nAfIvdT5eE:-KgFSosvR-nAfIvdT5eF:b-p7jw2o) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L89)):*
> ```JavaScript
> 
> /**
>  * Returns the current user logged in from the current app state, 
> ```

add @description

---

*[src/js/actions/GetDataActions.js, line 117 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSt2QJqtR9rW6QoEm:-KgFSt2QJqtR9rW6QoEn:b-wxz8tc) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L117)):*
> ```JavaScript
>     if (fs.existsSync(tCProjectsSaveLocation)) {
>         if (projectPath != tCProjectsSaveLocation) {
>             var continueCopy = confirm("This project is saved elsewhere on your computer. \nDo you want to overwrite it?");
> ```

does confirm work this way or does it need to be window.confirm()??

---

*[src/js/actions/GetDataActions.js, line 213 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFT9RfuyPYiz_LY9W2:-KgFT9RgqAIbkMcvlotl:b-dknfq4) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L213)):*
> ```JavaScript
> /**
>  * 
>  * @param {*} projectPath - Path in which the USFM project is being loaded from 
> ```

add variable type
example: @param {string}

---

*[src/js/actions/GetDataActions.js, line 238 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU6T5tcgSOnpfdZ19:-KgFU6T5tcgSOnpfdZ1A:b-v0dhsq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L238)):*
> ```JavaScript
> /**
>  * 
>  * @param {*} projectPath - Path in which the USFM project is being loaded from
> ```

add variable type 

---

*[src/js/actions/GetDataActions.js, line 251 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU4DeL5HEgXY1vpLE:-KgFU4DeL5HEgXY1vpLF:brkgpy2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L251)):*
> ```JavaScript
> 
> /**
>  * Starts loading a project that has a standard manifest created.
> ```

add @description tag

---

*[src/js/actions/GetDataActions.js, line 278 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU1Wuw2sWEOW3Uvu-:-KgFU1Wuw2sWEOW3Uvu0:brkgpy2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L278)):*
> ```JavaScript
> /**
>  * Displays the currently loaded tools in the app, if 
>  * project is a titus or ephisians, or if the userdata
> ```

add @description tag

---

*[src/js/actions/GetDataActions.js, line 384 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTQwk65C8VdCXONKi:-KgFTQwk65C8VdCXONKj:b-6xwfno) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L384)):*
> ```JavaScript
> /**
>  * 
>  * @param {*} parsedUSFM 
> ```

add variable/param type

---

*[src/js/actions/GetDataActions.js, line 410 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTzsi1rJEKFeql49y:-KgFTzsi1rJEKFeql49z:b-v0dhsq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L410)):*
> ```JavaScript
> 
> /**
>  * 
> ```

add variable type 

---

*[src/js/actions/GetDataActions.js, line 434 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTzAqP4jdksMPrSpk:-KgFTzAqP4jdksMPrSpl:b-v0dhsq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019 [...]

2017-03-27 19:54 UTC, RoyalSix commented
Review status: 52 of 58 files reviewed at latest revision, 62 unresolved discussions, some commit checks broke.

---

*[src/js/ModuleApi.js, line 244 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFPycGdleWzuOU04tQ:-KgFwCnsAd5izE9lw44a:b5l5fd1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/ModuleApi.js#L244)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we want to keep  '/manifest.json' instead 
</blockquote></details>

I'm not using the api, that changed on a code base wise var change. You can dis regard it.

---

*[src/js/actions/CoreActionConsts.js, line 17 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFRByPWKdDHC18jECr:-KgFwQxC4gk8Y2gHH1ZH:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/CoreActionConsts.js#L17)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this is written twice ^^^
</blockquote></details>

Done.

---

*[src/js/actions/CoreActionsRedux.js, line 251 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFRmbMjkghOR1YC_F6:-KgFwb3tQa_Wsy_klq2R:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/CoreActionsRedux.js#L251)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

Do we need to get rid ofn the commented code?
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 29 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSSxn-1gDLiLULqKN:-KgFwe7qyRFQvwIJT7WF:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L29)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should all be constants not varaibles (let)
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSbAem6c3KPldyWZV:-KgG96evYz1YvRxkGDuA:bs9aawb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L42)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

maybe add @description
</blockquote></details>

No need, its still per JS Doc syntax

---

*[src/js/actions/GetDataActions.js, line 117 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSt2QJqtR9rW6QoEm:-KgG94tJ1Pag-PYlfqwG:b-xt9nsf) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L117)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

does confirm work this way or does it need to be window.confirm()??
</blockquote></details>

Works.

---

*[src/js/actions/GetDataActions.js, line 213 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFT9RfuyPYiz_LY9W2:-KgG9HEQRuD8qWIf5ZVo:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L213)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add variable type
example: @param {string}
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 238 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU6T5tcgSOnpfdZ19:-KgG9I9XEWih1_MjSiQ2:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L238)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add variable type 
</blockquote></details>

Done.

---

*[src/js/actions/ResourcesActions.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFV3jb2YLWGXhdCVL4:-KgG9aOy0oek2H6YlW4L:bp3huxb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/ResourcesActions.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this is a separate action this should not be part of addNewResource. it should be a separate action.

addCurrentCheckIndex() (separate action)
</blockquote></details>

Refactored with sending down am object with a few actions to handle this so that it can be specific

---

*[src/js/actions/ResourcesActions.js, line 23 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFVE0NcjxVIDDkneZS:-KgG9urL-keKMLJZYR7A:bp3huxb) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/ResourcesActions.js#L23)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this is a separate action this should not be part of addNewResource. it should be a separate action.

addCurrentGroupIndex() (separate action)
</blockquote></details>

Refactored with sending down am object with a few actions to handle this so that it can be specific

---

*[src/js/components/core/GitApi.js, line 45 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFViBCYvYisTczSjZK:-KgGGEt4gdMHjcis7eWa:b9c3zv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/GitApi.js#L45)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should probably be a helper
</blockquote></details>

This can be done in a future PR.

---

*[src/js/components/core/SwitchCheck.js, line 10 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFVzPonOu3lJGkrqQH:-KgGGJLxhuoyQPkLEUg9:b-ucfknh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/SwitchCheck.js#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

good job!n
</blockquote></details>

Thanks!

---

*[src/js/components/core/login/GogsApi.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFW7d0HJbi6Hap_OBm:-KgGGPKrzDQhBTOOo-r2:b-8ayu6x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/login/GogsApi.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we should make this file a helper
</blockquote></details>

Agree

---

*[src/js/components/core/navigation_menu/SubMenu.js, line 26 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFWD8kaUDXefUzt3bU:-KgGGwF54dUKQrOON2ZH:b-8oidwm) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/navigation_menu/SubMenu.js#L26)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did we change this to lower case?
</blockquote></details>

Not sure, this is broken anyways.

---

*[src/js/components/core/reports/ReportFilters.js, line 154 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFWOi8nB-IyMmFM0Ft:-KgGHFgTgQEj-bE07vr_:b-ir3tyj) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01be06b0cd6033cddcfebb3555da8d92dba86321/src/js/components/core/reports/ReportFilters.js#L154)):*
<deta [...]

2017-03-27 22:39 UTC, mannycolon commented
Reviewed 14 of 14 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 42 unresolved discussions, some commit checks broke.

---

*[src/js/ModuleApi.js, line 244 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFPycGdleWzuOU04tQ:-KgGuZElCYsyWAkRjF9l:bphp9ii) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/ModuleApi.js#L244)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I'm not using the api, that changed on a code base wise var change. You can dis regard it.
</blockquote></details>

so, I don't think I understand what you mean lol

---

*[src/js/actions/CheckStoreActions.js, line 37 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgGrnthP0tssc9HsJuK:-KgGrntitnRmn_ABQInP:bi766be) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/CheckStoreActions.js#L37)):*
> ```JavaScript
> export function updateCurrentCheck(newCheck) {
>   return ((dispatch) => {
>     //TODO
> ```

dont forget about the TODO lol

---

*[src/js/actions/GetDataActions.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSbAem6c3KPldyWZV:-KgGsRPovTwV6EcFQms4:b-t4ch33) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L42)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

No need, its still per JS Doc syntax
</blockquote></details>

i still think it will make it more consistent 

---

*[src/js/actions/GetDataActions.js, line 30 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgGsEFGZYmeVQpIFea6:-KgGsEFGZYmeVQpIFea7:b-of7d81) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/GetDataActions.js#L30)):*
> ```JavaScript
> 
> const api = window.ModuleApi;
> const GIT = require('../components/core/GitApi.js');
> ```

you can use import for Git

---

*[src/js/actions/ResourcesActions.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFV3jb2YLWGXhdCVL4:-KgGt7S0ttLQrsL0a-y9:b7l764r) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/ResourcesActions.js#L19)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Refactored with sending down am object with a few actions to handle this so that it can be specific
</blockquote></details>

why are you sending the resource data as a parameter to that action??

---

*[src/js/components/core/GitApi.js, line 60 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFVhYcquuNttrZPkcU:-KgGupL-lg02wJadIJji:bup73ps) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/GitApi.js#L60)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should probably be a helper
</blockquote></details>

i agree

---

*[src/js/pages/app.js, line 4 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFYswTEXTTRvNYGJxe:-KgGtoqbWS6EzRL1N57t:b-rrae6w) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/pages/app.js#L4)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Removed, next story will be to refactor app.js :)
</blockquote></details>

we could move this to the data persistence implementation and added to the preloadedState

---

*[src/js/pages/app.js, line 94 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFZ8V6fIfrsS3Z4I3G:-KgGu0Ut0PKeqmnp6C6-:b-q7hbp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/pages/app.js#L94)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

To check if last project will be loaded, the logic is still correct but it needs to be updated.
</blockquote></details>

ok, i m thinking we could move this up the tree to the preloadedState what do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-27 22:42 UTC, mannycolon approved these changes

2017-03-27 22:45 UTC, mannycolon commented
@ihoegen @EllDoubleYew @klappy

2017-03-27 23:17 UTC, ihoegen requested changes
Also: Remove submodule commits by merging with develop

2017-03-27 23:17 UTC, ihoegen commented on src/js/ModuleApi.js
> +      projectSaveLocation += '/tc-manifest.json';
Leave as manifest.json

2017-03-27 23:17 UTC, ihoegen commented on src/js/stores/CoreStore.js
> +  getcurrentCheckNamespace() {
Can we camelCase this

2017-03-27 23:17 UTC, ihoegen commented on src/js/actions/CoreActions.js
>      });
Could probably remove `sendAlertResponse` also, right?

2017-03-27 23:17 UTC, ihoegen commented on src/js/components/core/MenuBar.js
> -          clearPreviousData();
This function could probably use a little more reworking

2017-03-27 23:17 UTC, ihoegen commented on src/js/actions/RecentProjectsActions.js
> +let consts = require('./CoreActionConsts');
Should probably use `consts` instead of `let`

2017-03-27 23:17 UTC, ihoegen commented on src/js/components/core/login/GogsApi.js
> +  return api.createUser(user, auth, true)
`auth` will not be defined because it is passed down by the `userManager` function.

2017-03-27 23:17 UTC, ihoegen commented on src/js/utils/helpers.js
> + * @param {*} path
I don't believe `*` is a valid type

2017-03-27 23:49 UTC, ihoegen commented
@royalsix, also the tests are failing for Upload.js because they are requiring UploadMethods.js which no longer exists

2017-03-28 00:04 UTC, RoyalSix commented
Review status: 55 of 60 files reviewed at latest revision, 47 unresolved discussions, some commit checks broke.

---

*[src/js/actions/CoreActions.js, line 80 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs65zApby8vu4mFW-r3-80:-KgH5rmzJntiyll34lr1:bhcsi0u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/CoreActions.js#L80)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Could probably remove `sendAlertResponse` also, right?
</blockquote></details>

That is unrel

---

*[src/js/actions/GetDataActions.js, line 384 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTQwk65C8VdCXONKi:-KgH61OHSusfXculMwbi:b-lbut5x) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L384)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add variable/param type
</blockquote></details>

What do you mean?

---

*[src/js/actions/ResourcesActions.js, line 19 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFV3jb2YLWGXhdCVL4:-KgH6EcRQ-gD4NIaXyfV:b8wot8m) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/ResourcesActions.js#L19)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you sending the resource data as a parameter to that action??
</blockquote></details>

Thats the parameters the action takes? Not sure why it'd be something else 

---

*[src/js/components/core/login/GogsApi.js, line 38 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs66CEUlnDg2mCHU-r3-38:-KgH9MNdlfXR1Bcukoww:bdiogf1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/components/core/login/GogsApi.js#L38)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

`auth` will not be defined because it is passed down by the `userManager` function. 
</blockquote></details>

Nice catch

---

*[src/js/reducers/coreStoreReducer.js, line 6 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgF_-v3e5rfqEMeJ1Eu:-KgH9sOOub-ghhu-vGtW:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/reducers/coreStoreReducer.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why are you using a string???? should this be a boolean??
</blockquote></details>

Done.

---

*[src/js/reducers/resourcesReducer.js, line 5 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgF_UItcn4vpt3XjLdH:-KgHALCn-X1LXH0eRhN3:b-9bzi40) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/01be06b0cd6033cddcfebb3555da8d92dba86321/src/js/reducers/resourcesReducer.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you remove this???
</blockquote></details>

Resources is such a general term, the user is already specifying a "namespace" for the data why abstracted a level further?

---

*[src/js/reducers/resourcesReducer.js, line 20 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgF__uUBFKRT7QibJD8:-KgHAa_KJOKIKOzyjnaB:bdni78n) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/reducers/resourcesReducer.js#L20)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

again this should only be used for resources

example:
translationNotes and translationWords sectionList and/or wordList 

</blockquote></details>

exactly

---

*[src/js/stores/CoreStore.js, line 161 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs67Gr6MXE_PbyEC-r3-161:-KgHAiWo3EKbXpfKDJGo:b-105lrq) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/stores/CoreStore.js#L161)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Can we camelCase this
</blockquote></details>

This isn't being used

---

*[src/js/utils/helpers.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgF_uuVebF0yy07RQ3x:-KgHApQWmJVXgeT19o1A:b-4nnwdp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/utils/helpers.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should be in the helpers folder, not the utils folder 

also, they should all be in separate files and then added to index.js in helpers foldern
</blockquote></details>

I implemented this before the helpers folder existed, the new folder is too mainstream

---

*[src/js/utils/helpers.js, line 24 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs6L4vUVcCuqOqYW-r3-24:-KgHC6gSBViQKjXxtZlE:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/utils/helpers.js#L24)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I don't believe `*` is a valid type
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:14 UTC, klappy commented
*[src/js/actions/CheckStoreActions.js, line 4 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHFmwUQYi5z-aBJ-4e:-KgHFmwUQYi5z-aBJ-4f:b-jmhotr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/135481f23c20f1d059740fbd4e77b6eec45b2195/src/js/actions/CheckStoreActions.js#L4)):*
> ```JavaScript
> import BooksOfBible from '../components/core/BooksOfBible'
> const CoreStore = require('../stores/CoreStore.js');
> import * as CoreActionsRedux from './CoreActionsRedux.js';
> ```

BTW: That's cool!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:18 UTC, klappy commented
*[src/js/actions/GetDataActions.js, line 278 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU1Wuw2sWEOW3Uvu-:-KgHGftn5iqsM7nIioDQ:bxx3jim) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L278)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add @description tag
</blockquote></details>

manny, is like the grammar police, but for consistency :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:19 UTC, klappy commented
*[src/js/actions/GetDataActions.js, line 384 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTQwk65C8VdCXONKi:-KgHGuGFcDkPqq8GRYcd:b-sj03af) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L384)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

I'm not sure what he means either for this one...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:19 UTC, klappy commented
*[src/js/actions/GetDataActions.js, line 410 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTzsi1rJEKFeql49y:-KgHH2HRdv9LDKOAHd7f:b-wjiylx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L410)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add variable type 
</blockquote></details>

isn't string the variable type?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:22 UTC, klappy commented
*[src/js/actions/RecentProjectsActions.js, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs66CEUlnDg2mCHF-r3-1:-KgHHgq-zjqCVsqq2_1_:b8e4jgv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/RecentProjectsActions.js#L1)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Should probably use `consts` instead of `let`
</blockquote></details>

is there a reason for the change to let?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:25 UTC, klappy commented
*[tests/static/3john/checkdata/common.tc, line 0 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHIKMWhop7NhlMo57B:-KgHIKMWhop7NhlMo57C:brhtuzr) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/135481f23c20f1d059740fbd4e77b6eec45b2195/tests/static/3john/checkdata/common.tc#L0)):*
Is there a reason this one was updated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:26 UTC, klappy commented
*[src/js/stores/CoreStore.js, line 161 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs67Gr6MXE_PbyEC-r3-161:-KgHIYTI5XcETbERZbmd:b-w73lvl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/stores/CoreStore.js#L161)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

This isn't being used
</blockquote></details>

should we remove it then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:27 UTC, klappy commented
*[src/js/reducers/loaderReducer.js, line 14 at r4](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHItQ3TeG3OzFOWVVJ:-KgHItQ4jpGpQHJyxJpQ:bgcxtuh) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/135481f23c20f1d059740fbd4e77b6eec45b2195/src/js/reducers/loaderReducer.js#L14)):*
> ```JavaScript
>     case consts.TOGGLE_LOADER_MODAL:
>       return { ...state, show: action.show || !state.show }
>       break;
> ```

BTW: thanks for catching the omission of break

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:33 UTC, klappy commented
*[src/js/components/core/create_project/CheckDataGrabber.js, line  at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFW27HXse_KHicU2Rk:-KgHK7ifyIJRpg6aRB3P:bzbe3hx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/create_project/CheckDataGrabber.js#L)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

nice done!
</blockquote></details>

woohoo! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:34 UTC, klappy commented
*[src/js/components/core/login/GogsApi.js, line 38 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs66CEUlnDg2mCHU-r3-38:-KgHKKVhQZ7cSz8EvOjb:bf3htsl) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/components/core/login/GogsApi.js#L38)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Nice catch
</blockquote></details>

Could this be why it wasn't working for so long?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:35 UTC, klappy commented
*[src/js/components/core/navigation_menu/SubMenu.js, line 26 at r5](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHKfo6nom5g9bwjCdS:-KgHKfo6nom5g9bwjCdT:b-ymcgh2) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/d6e69ce028b36412552219c89f1ab1ba2b92dab2/src/js/components/core/navigation_menu/SubMenu.js#L26)):*
> ```JavaScript
> 
>   goToNext() {
>     let currentNamespace = CoreStore.getcurrentCheckNamespace();
> ```

is there a reason we dropped the camel case here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:38 UTC, klappy commented
Reviewed 27 of 59 files at r1, 9 of 14 files at r2, 1 of 1 files at r3, 6 of 11 files at r4.
Review status: 53 of 57 files reviewed at latest revision, 51 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:41 UTC, klappy commented
Reviewed 4 of 59 files at r1, 3 of 14 files at r2.
Review status: 53 of 57 files reviewed at latest revision, 51 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 00:49 UTC, RoyalSix commented on src/js/components/core/MenuBar.js
> -          clearPreviousData();
Yes, this is broken right now

2017-03-28 00:53 UTC, RoyalSix commented
Review status: 51 of 57 files reviewed at latest revision, 52 unresolved discussions.

---

*[src/js/ModuleApi.js, line 244 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFPycGdleWzuOU04tQ:-KgHHINPesKM3A9COh26:b-hdkyc5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/ModuleApi.js#L244)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

so, I don't think I understand what you mean lol
</blockquote></details>

This function is broken, its unrelated to my PR

---

*[src/js/actions/CoreActions.js, line 80 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs65zApby8vu4mFW-r3-80:-KgHHYU_8Jsbh4VLW2dg:b-idefjn) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/CoreActions.js#L80)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

That is unrel
</blockquote></details>

This file is getting deleted soon, we will remove it in a different PR

---

*[src/js/actions/GetDataActions.js, line 42 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSbAem6c3KPldyWZV:-KgHJ_-s4awtWrWhcvZg:bb74x83) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L42)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

i still think it will make it more consistent 
</blockquote></details>

True

---

*[src/js/actions/GetDataActions.js, line 52 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSfLW6d0-GPaPqJvx:-KgHJbjOWapn89ffyhGE:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L52)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here maybe add @description
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 62 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSjx3e2AvrZca1N9B:-KgHJc9eeJfKwDokE_66:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L62)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here ^^^  add @description
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 75 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFShvm7G2XwWOTpEyH:-KgHJcaLXqdd7e5EHF0E:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L75)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here maybe add @description
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 89 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFSosvR-nAfIvdT5eE:-KgHJczvAcB-r2RtxM5_:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L89)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add @description
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 251 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU4DeL5HEgXY1vpLE:-KgHJdMYmVfwgF-3TUJG:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L251)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add @description tag
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 278 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFU1Wuw2sWEOW3Uvu-:-KgHJepQHp8Jo71Tc3U4:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L278)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

manny, is like the grammar police, but for consistency :)
</blockquote></details>

Done.

---

*[src/js/actions/GetDataActions.js, line 30 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgGsEFGZYmeVQpIFea6:-KgHHm4TUhvhZtmL6euQ:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/GetDataActions.js#L30)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

you can use import for Git
</blockquote></details>

Done.

---

*[src/js/actions/RecentProjectsActions.js, line 1 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs66CEUlnDg2mCHF-r3-1:-KgHJrprLTCu4RXvpWkM:b-mi720q) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/actions/RecentProjectsActions.js#L1)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

is there a reason for the change to let?
</blockquote></details>

For irony...haha updated

---

*[src/js/components/core/GitApi.js, line 74 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFVh2Xqm_70dNIfvzW:-KgHJzrG1DcKzLvdE-jY:b20sm1u) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/components/core/GitApi.js#L74)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this should probably be a helper
</blockquote></details>

Yes, this can be done in a separate PR

---

*[src/js/pages/app.js, line 94 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFZ8V6fIfrsS3Z4I3G:-KgHKBFVxRdUjQesRJIq:bstbde1) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/pages/app.js#L94)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

ok, i m thinking we could move this up the tree to the preloadedState what do you think?
</blockquote></details>

Yes, again separate PR

---

*[src/js/reducers/checkStoreReducer.js, line 22 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFZuoKOaV_aYMOTFhE:-KgHKFjW9QsEdtnJWNJP:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/reducers/checkStoreReducer.js#L22)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we use the consts.XXXXX_XXXX
</blockquote></details>

Done.

---

*[src/js/reducers/checkStoreReducer.js, line 32 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFZvLEmYoJNPPcL5MH:-KgHKG6c9p0JfyTD9RAM:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/reducers/checkStoreReducer.js#L32)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

can we use the consts.XXXXX_XXXX
</blockquote></details>

Done.

---

*[src/js/reducers/checkStoreReducer.js, line 37 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFZw5f0Uq5i1HIL3T-:-KgHKJB0cHMoQTxSzfua:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/reducers/checkStoreReducer.js#L37)):*
<de [...]

2017-03-28 00:59 UTC, RoyalSix commented
Review status: 51 of 57 files reviewed at latest revision, 52 unresolved discussions.

---

*[tC_apps/ScripturePane, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFaNRSoZQGAIKTrrSf:-KgHQDV0rIm64ABUjuwp:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/tC_apps/ScripturePane#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

please remove this commit from the scripture pane 

you're overwriting the latest version of scripturePane 
</blockquote></details>

Done.

---

*[tC_apps/TranslationHelps, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFac_QMm2Grad1W5gk:-KgHQBikyWqxaUiIsH-h:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/tC_apps/TranslationHelps#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here remove this

you're overwriting the latest commit of the tool
</blockquote></details>

Done.

---

*[tC_apps/translationWords, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFal3Wq_Nb3YpnkZCm:-KgHQCDaSBsH-WRjTqj9:b-896fix) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/tC_apps/translationWords#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same here remove this

you're overwriting the latest commit of the tool
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 01:46 UTC, mannycolon commented
Reviewed 3 of 11 files at r4, 5 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

*[src/js/ModuleApi.js, line 244 at r3](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFOs65zApby8vu4mFT-r3-244:-KgHXlyKg2_UwQRCbahz:b-mju8xi) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/5098747099f3a4c01ad749edce013c6e1a089057/src/js/ModuleApi.js#L244)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

Leave as manifest.json
</blockquote></details>

ok lol

---

*[src/js/actions/GetDataActions.js, line 384 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTQwk65C8VdCXONKi:-KgHYf7IAdsFrz_F613T:b-ikrse5) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L384)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I'm not sure what he means either for this one...
</blockquote></details>

you already addressed it that's why it doesn't make sense now lol

---

*[src/js/actions/GetDataActions.js, line 410 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgFTzsi1rJEKFeql49y:-KgHYlCRtHw0MFfuWpFY:bnj7hl0) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/actions/GetDataActions.js#L410)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

isn't string the variable type?
</blockquote></details>

same as above

---

*[src/js/actions/GetDataActions.js, line 4 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHXt-ypotP9EcMaHcd:-KgHXt-ypotP9EcMaHce:b-ge2lju) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L4)):*
> ```JavaScript
>  * @file These are the actions that load a tC project from
>  * the manifest.json to the tools being loaded into the store
>  * @author RoyalSix (I ate Seven)
> ```

you ate seven???

---

*[src/js/actions/GetDataActions.js, line 21 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHY-M5odeFYzQgYy8k:-KgHY-M5odeFYzQgYy8l:b-g89jtv) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L21)):*
> ```JavaScript
> import * as ModalActions from './ModalActions';
> import * as ToolsActions from './ToolsActions';
> import * as LoadHelpers from '../helpers/LoadHelpers';
> ```

well done!!! lmao

---

*[src/js/actions/GetDataActions.js, line 43 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYBQRa_6MmmxeHCk8:-KgHYBQRa_6MmmxeHCk9:bhldvlx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L43)):*
> ```JavaScript
> 
> /**
>  * @description Sends project path to the store
> ```

lol thanks

---

*[src/js/actions/GetDataActions.js, line 53 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYD39KMDNWg_lJJ4U:-KgHYD39KMDNWg_lJJ4V:bhldvlx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L53)):*
> ```JavaScript
> 
> /**
>  * @description Sends project manifest to the store
> ```

lol thanks

---

*[src/js/actions/GetDataActions.js, line 63 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYEFgU7yCVCwDzsiI:-KgHYEFgU7yCVCwDzsiJ:bhldvlx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L63)):*
> ```JavaScript
> 
> /**
>  * @description Sends project parameters to the store
> ```

lol thanks

---

*[src/js/actions/GetDataActions.js, line 76 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYFPmSTdDJL0b-2xY:-KgHYFPmSTdDJL0b-2xZ:bhldvlx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L76)):*
> ```JavaScript
> 
> /**
>  * @description Formats and saves manifest according to tC standards, 
> ```

lol thanks

---

*[src/js/actions/GetDataActions.js, line 90 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYGbng9VpRe8ILp75:-KgHYGboHnnuZVVBmyYO:bhldvlx) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L90)):*
> ```JavaScript
> 
> /**
>  * @description Returns the current user logged in from the current app state, 
> ```

lol thanks

---

*[src/js/actions/GetDataActions.js, line 135 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYIwkXIOrf_0y8aFM:-KgHYIwkXIOrf_0y8aFN:bfayusz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L135)):*
> ```JavaScript
> /**
>  * @description Starter function to load a project from a folder path or link.
>  * 
> ```

maybe remove this empty line lol

---

*[src/js/actions/GetDataActions.js, line 169 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYM23wiHgGqQHT7WC:-KgHYM23wiHgGqQHT7WD:bfayusz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L169)):*
> ```JavaScript
> /**
>  * @description Sets up the folder in the tC save location for a USFM project
>  * 
> ```

maybe remove this empty line lol

---

*[src/js/actions/GetDataActions.js, line 184 at r7](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgHYMi6abKmKO4ipjwO:-KgHYMi6abKmKO4ipjwP:bfayusz) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/6cdba88c4dfc94dcad1474aeebb1806a04b82c6e/src/js/actions/GetDataActions.js#L184)):*
> ```JavaScript
> /**
>  * @description Sets up a USFM project manifest according to tC standards.
>  * 
> ```

maybe remove this empty line lol

---

*[src/js/helpers/LoadHelpers.js, line 1 at r1](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956#-KgF_uuVebF0yy07RQ3x:-KgHZWn9DJvkLAzQwdhJ:b-cfawtp) ([raw file](https://github.com/unfoldingword-dev/translationcore/blob/70dc5b49080cbce8e1a0ad9501e76e019a1c2a08/src/js/helpers/LoadHelpers.js#L1)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I implemented this before the helpers folder existed, the new folder is too mainstream
</blockquote></details>

why mainstream ?? lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/unfoldingword-dev/translationcore/956)*
<!-- Sent from Reviewable.io -->

2017-03-28 01:53 UTC, ihoegen approved these changes

2017-03-28 04:13 UTC, merged